
name: greeting workflow

on: [push]

jobs:
    greet:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the code
              uses: actions/checkout@v4

            - name: Print Hello
              run: echo "Hello from GitHub Actions!"        