name: Job Outputs

on: [push, workflow_dispatch]

jobs:
  first-job:
    runs-on: ubuntu-latest
    outputs:
      current_date: ${{ steps.get_date.outputs.date }}
    steps:
      - id: get_date
        run: echo "date=$(date)" >> $GITHUB_OUTPUT

  second-job:
    runs-on: ubuntu-latest
    needs: first-job
    steps:
      - run: echo "The date passed from the first job is ${{ needs.first-job.outputs.current_date }}"
