name: Manual Trigger Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the environment'
        required: true
        type: choice
        options:
          - staging
          - production
        default: 'staging'

jobs:
  run-manual-task:
    runs-on: ubuntu-latest
    steps:
      - name: Print Environment
        run: echo "The selected environment is ${{ inputs.environment }}"
